name: weather_app
description: A new Flutter project using BLoC and clean architecture.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  lottie: ^2.2.0
  fl_chart: ^0.55.1
  animated_splash_screen: ^1.3.0
  geolocator: ^9.0.1
  geocoding: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/ 
    - assets/animation/
